styled the footer.html file
Appers-lab/billihomes-frontend pull request #15
Opened 2021-06-03 17:25 UTC by Chukwudalu

I made changes to the _footer.scss and _mls.scss as required. I also made a little change to the footer.html file as i was not really sure if i was allowed to really make changes to that file as per the instructions in the issue. 

However, let me know if i am allowed to make more changes to the footer.html file , in order to style it better. @pmvald

2021-06-03 18:13 UTC, pmvald requested changes
I reviewed and left comments

2021-06-03 18:13 UTC, pmvald commented on -sass/project-cmps/_mls.scss
> +  height: 20vh;
for heights set a fixed value in px unit

2021-06-03 18:13 UTC, pmvald commented on -sass/project-cmps/_mls.scss
> +  padding: 22px 0;
No need for padding. Maybe we just enclose the content in a `<dic class="container">` (in the html) in order to align with the rest of components in the page. To create space between this component and others use margin-top and margin-bottom instead

2021-06-03 18:13 UTC, pmvald commented on -sass/project-cmps/_mls.scss
>      width: 106px;
use width and height which is exacatly the same size as the original .gif file.

2021-06-03 18:13 UTC, pmvald commented on -sass/styles/_footers.scss
> +$link-color: rgb(214, 205, 205);
lets build them into scss (theme) variables. rename them to footer-bg-color and footer-text-color and footer-link-color.

2021-06-03 18:13 UTC, pmvald commented on -sass/styles/_footers.scss
> +    height: 40vh;
height should depend on the content. No need to set a fixed height

2021-06-03 18:13 UTC, pmvald commented on -sass/styles/_footers.scss
> +    padding: 60px 0;
No need. Use container class to wrap the footer contents. But if you want to create space between footer and the previous element then use margin-top

2021-06-03 18:13 UTC, pmvald commented on -sass/styles/_footers.scss
> +    & .icon{
Class name should be renamed based on BEM, like `ss-footer__icon`

2021-06-03 18:13 UTC, pmvald commented on -sass/styles/_footers.scss
> +.ss-footer{
Lets rename it to `s-footer`. This class is a general purpose class and should be in Layer 1 (not in project specifit layer 2)

2021-06-03 18:13 UTC, pmvald commented on -sass/styles/_footers.scss
> +    & .copyright-links{
Should be renamed based on BEM

2021-06-03 18:13 UTC, pmvald commented on -sass/styles/_footers.scss
> +        a{
Maybe no need for these, they can follow the footer link style.

2021-06-03 18:13 UTC, pmvald commented on tasks/task-007/footer.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIh
Lets find some icon fonts that can be used offline. Take a look at Bootstrap 5 icons and see if we can just download them. We want our website work offline as well.

2021-06-03 20:41 UTC, Chukwudalu commented
I have made the required changes. Let me know if i missed something @pmvald

2021-06-04 04:03 UTC, pmvald requested changes
@Chukwudalu It's better now. I left code review

2021-06-04 04:03 UTC, pmvald commented on -sass/styles/_footers.scss
> +    align-items: center;
No need to define footer as flex. Since we use a .container div inside it it automatically centers the contents (this .container class is the same as the one in bootstrap). And then inside the container we use a "row" deivision. Note that "row" class is flex itself. So maybe all we need for footer is color, background-color, and maybe padding which you added below

2021-06-04 04:03 UTC, pmvald commented on -sass/styles/_footers.scss
> +        &__child{
no need, see the comments on the html file

2021-06-04 04:03 UTC, pmvald commented on -sass/styles/_footers.scss
> +            &__icon{
move it out of __contact as a standalone element class

2021-06-05 04:12 UTC, Chukwudalu commented
I have made the required changes @pmvald

2021-06-05 04:13 UTC, Chukwudalu commented
and made a new pull request @pmvald

2021-06-07 17:34 UTC, pmvald commented
@Chukwudalu I made some improvements. Please take a look at my changes to get a better idea of our design style. In particular notice:
1. I used padding for both footer instead of "display: flex, align-item: center, etc"  In general to align items in the center (horizontally) we just wrap them within a .container class. We usually don't need to align vertically in the center, but if we the may be flex would be solution. 
2. I reduced the nestings, particularly the row with icons was made into one flex row instead of a row of rows.
3. As you see the layout is done mostly by layer 0 classes (container, d-flex, etc.) We mainly had to add color, background-color and font-sizes, etc.
4. I also  downloaded the bootstrap icons and placed them in the font folder. Now everyone can use the icons. I also used <i> instead of <img> for icons. This way we can change the color and font-size of icons as well.

2021-06-07 17:39 UTC, pmvald approved these changes

2021-06-07 17:40 UTC, merged

2021-06-07 21:50 UTC, Chukwudalu commented
Ok thank you @pmvald