Task 11 Additions
Appers-lab/billihomes-frontend pull request #25
Opened 2021-06-09 19:26 UTC by navjot-chahal

Task 11 is partially complete. Only the scalability needs to be added. I was not able to put the CSS file to the asked directory, so i just put it into the task 11 folder.

2021-06-10 16:33 UTC, pmvald requested changes
@navjot-chahal I made some comments and code review. Please review our design guide one more time. There are several issues with the using sass.

2021-06-10 16:33 UTC, pmvald commented on -sass/styles/_partners.scss
> +// Grid initialization
Initialization? We don't have these concepts for css. Combine this block with the next for the class Grid

2021-06-10 16:33 UTC, pmvald commented on -sass/styles/_partners.scss
> +.Grid > dev{
It's a kind of convetion to use lower case for css classes. So call this grid.

That being said. In this task we do not need to define grid. We are already using bootstrap grid (see my html code where I use classes row and col-2). The purpose of class "s-partner-logos" (which you defined nowhere) is perhaps just to add the dotted borders around the logos (see the canvas model)

2021-06-10 16:33 UTC, pmvald commented on tasks/task-011/index.html
> +    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymo
No need. Do not include include 3rd party css. We already included (part of) bootstrap in our Layer 0 css (namely _layouts.scss).

2021-06-10 16:33 UTC, pmvald commented on tasks/task-011/index.html
> +    <link rel="stylesheet" href="./main.css">
You need to include the bundle.css which is created when you run `sass-start` batch file in the project root. This bundle.css will include your classes as well (you still need to import your scss file, in this case _partners.scss, into the _styles.scss). Do not include css directly

2021-06-10 16:33 UTC, pmvald commented on tasks/task-011/index.html
> +            <div class="Grid__logo1">
__logo1, __logo2? No need, just __logo

2021-06-10 16:33 UTC, pmvald commented on -sass/bootstrap5/bootstrap-grid.css
> +/*!
Something is wrong with using sass here. Did you use the file `sass-start`? Yu shoud not create these css file in the -sass folder. Remove them all.

2021-06-10 23:32 UTC, pmvald commented on -sass/bootstrap5/bootstrap-grid.css
> +/*!
@navjot-chahal  The first and foremost step to become a developer is to stay away from anything Windows! You wanna install Ubuntu (you can install it side by side with Windows if you prefer. For example see [this guide](https://vitux.com/how-to-install-ubuntu-18-04-along-with-windows-10/)). Nevertheless, with windows or not, you have first to install [*npm* ](https://nodejs.org/en/), then install sass by running `npm install -g sass`. Then you should have a command sass in your terminal. It is then you can run the file `sass-start` (in windows you have to rename it `sass-start.bat` or `sass-start.sh` also would work ...)

2021-06-12 00:21 UTC, navjot-chahal commented on -sass/styles/_partners.scss
> +.Grid > dev{
@pmvald Thanks for clarifying. My apologies for confusing things. I have installed a virtual machine running Ubuntu now. I have spent a great amount of time analyzing here, and now I know that the two classes "row" and "col-2" are pre-defined in the sass file that was added when "sass-start" was initialized. So that resulted in the 6 columns layout that I attached here. So as per your instruction I need to add the dotted line between the logos and make it similar to the canvas sample "client" page. In order to achieve that I tried reverse-engineering the code behind the clients.html but was unable to do so as I could not locate the associated CSS/SASSfile. Can you help in identifying the steps needed here to find the associated style here? Apology for this long comment.
![image](https://user-images.githubusercontent.com/60498899/121759216-7c79c080-cad9-11eb-8473-7c102b37943b.png)

2021-06-12 19:07 UTC, navjot-chahal commented on -sass/styles/_partners.scss
> +.Grid > dev{
@pmvald Can you please advise?

2021-06-15 05:50 UTC, pmvald commented on -sass/styles/_partners.scss
> +.Grid > dev{
@navjot-chahal Try using the css style *border:1px dotted $grey* for the grid cells. This is basic css in fact

2021-06-19 21:12 UTC, navjot-chahal commented
@pmvald I have incorporated the changes. Please review my work. I had to go through hours of tutorials and theory to get the dotted border to show as asked. Thanks for your patience.

2021-06-21 17:04 UTC, pmvald commented
@navjot-chahal This is a very basic css task. Literally it needs only one line of code:

```css
.s-partner-logos {
   div {
     border: 1px dotted $light-grey;
   }
}
```

That's it! (to further improve it you can only apply right and bottom borders and make exceptions for border children using [nth-child css](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child)).

I recommend you do some review of basic css at w3 school first.

2021-06-21 17:04 UTC, closed without merging