Task-019
Appers-lab/billihomes-frontend pull request #26
Opened 2021-06-10 03:08 UTC by akaaariii

@pmvald I tried to follow the Mobilekit but I'm not sure if this design is what you're thinking of. Please let me know if I need to fix something. Thank you.

2021-06-10 16:50 UTC, pmvald requested changes

2021-06-10 16:50 UTC, pmvald commented on tasks/task-019/listview.html
> +      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
We already included bootstrap fonts in the project. it is in /font/bootstrap-icons.css. USe this local version instead.

2021-06-10 16:50 UTC, pmvald commented on -sass/styles/_lists.m.scss
> +  &__menu {
we should reuse the menu style defined in the _menu.scss (bootstrap) here. Parhaps we may not need to modify menu much here

2021-06-10 16:54 UTC, pmvald commented
@akaaariii 

I guess there are some misunderstanding here. Firsly, I forgot to mention that the <ul> must include <li>s, and then each <li> represents a row (or item) in the list view. Then within the li you are going to have all those <sections>s and <menu> ... I have attached a screenshot of what each class represents. For the menu part, I guess we already designed that in the boostrap _menu.scss and its design shoud suffice here (unless you find the padding too big ...) 

![listview](https://user-images.githubusercontent.com/31361906/121565512-5b2dad00-c9d1-11eb-9822-3949b73bf58d.png)

Once you are done, in your html add a few rows, one with image, one without image (similar to what mobilekit did for its demo of listview)

2021-06-11 06:22 UTC, akaaariii commented
@pmvald I totally misunderstood. Thank you for your suggestion and I fixed it. Could you check my code again, please? and let me know if I still need to change something. Thank you.

2021-06-11 18:24 UTC, pmvald requested changes
@akaaariii I made a commit to fix some problems: there was a min-width applied to the body which was originally from the desktop style. I moved that to the desktop styles. I also added a viewport tag in the html header. When designing mobile pages you can use the browser developer mobile view to see how it looks on the mobile. Here is an screenshot
![listview2](https://user-images.githubusercontent.com/31361906/121732522-37d53180-caa7-11eb-8def-d55799503c39.png)

I made a code review. I suggested to restructure the html so that we can make a partial border bottom for the lists with image. Also, as you can see from the screeshot, the menu items are too far from each other. They need to be closer to each other and also to the right border. Follow the mobilekit measuring (they are standard).

2021-06-11 18:24 UTC, pmvald commented on -sass/styles/_lists.m.scss
> +  border-bottom: 1px solid $light-grey;
we add border to some child element to get a partial bottom border (in case of image)

2021-06-11 18:24 UTC, pmvald commented on -sass/styles/_lists.m.scss
> +  &::after {
No need for this. I see that you want to add that partial bottom border. Maybe we need to re-structure the html so that we can add that border simply by a border bottom (see my comments on the html)

2021-06-11 18:24 UTC, pmvald commented on tasks/task-019/listview.html
> +    <div class="s-listview--left">
follow this structure:

```html

<!-- this block is flex -->
<ul class="s-listview">

  <section class="s-listview__img">
  </section>

 <!-- this section is flex gets a border bottom  -->
  <section class="s-listview__content">
    <section class="s-listview__title"> ... </section>
    <section class="s-listview__menu"> ... </section>
  </section>

</ul>
```

2021-06-12 21:00 UTC, akaaariii commented on -sass/styles/_lists.m.scss
> +  border-bottom: 1px solid $light-grey;
I moved `border-bottom` to the child element. We don't need `border-top`?

2021-06-15 05:45 UTC, merged

2021-06-15 05:49 UTC, pmvald commented
@akaaariii I made some changes, including some organisational changes related to _menu.scss. Other than that, the html file structure was incorrect (did not contain `<li>`, and also `<menu>` was used in the wrong place). Please read the specifications more carefully for the next time. It took me 1.5 hours to fix all these problems which is almost the time I needed to finish the task all by myself. Noe please take a look at my list.m.scss and tell me what changes I made, and what new things you can learn from it (pay special attention to the use of $spacer, which I thing we should use for all the spacing values in the future)

2021-06-15 14:41 UTC, akaaariii commented
@pmvald  I’m sorry for taking your time to fix the problems. I’ll read the specifications more carefully for the next time. But in this task, I couldn’t get what you were thinking. I just followed the structure that you mentioned in the comment. In your html code, you did not contain `<li>` either. About `<menu>`, you changed from `<menu class=“s-listview__menu”>` to `<section class=“s-listview__menu”>` , so I followed your changes. I guess there were some misunderstandings. I tried to style without making changes in the html file structure that you mentioned. But now, I see the html file structure is a bit different from what you mentioned. Honestly, I’m confused because you changed your own code. I’ll read the specifications more carefully but if it’s possible, could you please write more details? Otherwise, there is a difference between Mobilekit and your code, so I get confused like this time. I appreciate your consideration.

2021-06-15 17:26 UTC, pmvald commented
@akaaariii no problem. You can always change the html boilerplate if need be. It is given mainly as a starting point to demonstrate the main framework and elements, but it may not be 100% accurate as you can see. In fact as designer you have to design both the html and the css. For now I give the html structure just for training purposes. In the future I won't give the html, I would mainly describe the structure and the specify the top class name, etc and it is up to the designer to outline an html structure based on BEM and other css practices and then write css for it.