Task 23
Appers-lab/billihomes-frontend pull request #29
Opened 2021-06-11 18:09 UTC by YusukeYoshihiro

Updated Task 23 drawer slide panels
         `modified:   -sass/_styles.m.scss`
	`new file:   -sass/styles/_drawer.m.scss`
	`new file:   tasks/task-023/drawer.html`

2021-06-11 19:05 UTC, pmvald requested changes
@YusukeYoshihiro I made a commit to include the viewport and remove the desktop min-width that was added by mistake to the mobile version. 

A side note: For testing your design you can use the mobile view in the browser developer tools (you know that?)

2021-06-11 19:05 UTC, pmvald commented on -sass/styles/_drawer.m.scss
> +  background-color: rgba(0, 0, 0, 0.4);
Don't worry about the dark overlay. For now just slide the drawer in and out. We will add the dark overlay later through a separate process (this is because in our app we support multiple modals/drawers that can stack on each other. So the dark overlay is not added by individual modals but by a separate controller that checks whether all the modals are closed or not)

2021-06-11 19:05 UTC, pmvald commented on -sass/styles/_drawer.m.scss
> +  height: 100%;
this block represent the drawer itself. Reduce the width (like to 80% as you did for the content)

2021-06-14 15:08 UTC, YusukeYoshihiro commented
@pmvald Hi, Peter! I updated and Modified Task 23, please confirm it.

2021-06-15 02:28 UTC, pmvald reviewed
@YusukeYoshihiro It's good. Now please move to task 12 which is a more general version of this task. You can use your code here for that task. Link this pull request to task 12 and follow its instructions. Task 12 offers a more structured and generic version for modal and we can apply different animations to it. I'm trying to find the most minimalist way to make all kind of modals/dialogs ...

2021-06-18 09:03 UTC, pmvald requested changes
@YusukeYoshihiro I think you misunderstood. We are NOT making bootstrap modal, but a different one. I made some comments. Let me know if it's still not clear

2021-06-18 09:03 UTC, pmvald commented on tasks/task-012/modal.html
> +            <div class="s-modal__content--header">
I think you misunderstood the task. We don't want to follow the bootstrap design, rather the one stated in the task. Here I copy the html structure one more time:

```html
<!-- content wrapper: feel free to add more styles if need be (maybe add display:flex for better alignment?), but i guess these are enough. No need to make these styles into css class. They will be generated by the javascript modal controller -->
<div style="position:fixed; width:100%; height:100%; top:0; left:0; z-index:10; display:none">   

  

    <!-- this is the modal content element which you have to write style for -->
     <article class="s-modal">
         <!-- any content here, you may use Lorem text to fill it up ... -->
     </article>

  

</div>
```

So, the class *s-modal* is in fact out "modal body". The outer wrapper (the one with hard coded style) plays the same role as the modal and modal-dialogue in bootstrap. The style for this wrapper is pretty much fixed and I already hard coded that. The main thing is to apply styles to the *s-modal* to create animation, etc.

2021-06-21 18:46 UTC, pmvald commented
@YusukeYoshihiro Ok I'll do this task myself, it's a bit complicated. You please move to other tasks labelled "help wanted"

2021-06-23 04:49 UTC, closed without merging