Rodrigo
Appers-lab/billihomes-frontend pull request #30
Opened 2021-06-11 22:22 UTC by Fodrigoal

I hope that's what you were asking for.

2021-06-15 17:44 UTC, pmvald requested changes
@Fodrigoal I reviewed the code. There was a problem with using scss syntax. Please review scss syntax and follow my comments. thanks.

2021-06-15 17:44 UTC, pmvald commented on tasks/task-017/button-menu.html
> +        <!-- added 3 more icons -->
good!

2021-06-15 17:44 UTC, pmvald commented on -sass/styles/_menus.m.scss
> +button {
something is wrong here! If by this style you mean the button that is inside `s-btn-menu` then you should not use comma, just space! Also since we are using scss this button style should be inside the previous block of s-btn-menu.

2021-06-15 17:44 UTC, pmvald commented on -sass/styles/_menus.m.scss
> +button:hover {
same as above

2021-06-15 17:44 UTC, pmvald commented on -sass/styles/_menus.m.scss
> +i {
same as above

2021-06-15 17:44 UTC, pmvald commented on -sass/styles/_menus.m.scss
> +p {
same as above

2021-06-15 17:44 UTC, pmvald commented on -sass/styles/_menus.m.scss
> +    padding: 1em;
for spacing between elements use margin (see the design-guide.md)

2021-06-15 17:44 UTC, pmvald commented on -sass/styles/_menus.m.scss
> +    padding-top: 0.5em;
for spacing between elements use margin (see the design-guide.md)

2021-06-15 20:26 UTC, Fodrigoal commented on -sass/styles/_menus.m.scss
> +button {
ok!

2021-06-15 20:27 UTC, Fodrigoal commented on -sass/styles/_menus.m.scss
> +    padding-top: 0.5em;
Of course! My mistake.

2021-06-16 02:47 UTC, Fodrigoal commented
Hi @pmvald I've done some changes to the scss.

2021-06-16 23:51 UTC, pmvald requested changes
@Fodrigoal Better now. Please attend to the comments I made

2021-06-16 23:51 UTC, pmvald commented on -sass/styles/_menus.m.scss
> +    letter-spacing: 0;
no need

2021-06-16 23:51 UTC, pmvald commented on -sass/styles/_menus.m.scss
> +    height: 56px;
write all the spaces in terms of $spacer. Note that $spacer=16px. So this could be `4.5*$spacer`

2021-06-16 23:51 UTC, pmvald commented on -sass/styles/_menus.m.scss
> +    line-height: 1.2em;
As mentioned in the previous review, we use *margin* for elements spacing, not padding, line-height, etc.

2021-06-16 23:51 UTC, pmvald commented on -sass/styles/_menus.m.scss
> +        color: black;
No need for color. color will inherit from the parent (keeping the design minimal)

2021-06-16 23:51 UTC, pmvald commented on -sass/styles/_menus.m.scss
> +            color: #1E74FD;
no need. We don't have hover in mobile devices

2021-06-16 23:51 UTC, pmvald commented on -sass/styles/_menus.m.scss
> +        margin-top: 0.5em;
use $spacer for spacing

2021-06-17 05:01 UTC, Fodrigoal commented
I've noticed display (same as menu from _menus.scss) and position weren't necessary so I deleted them.

I have also deleted all the spacing because the layout still looks good and similar to Mobilekit without them.

2021-06-18 09:15 UTC, pmvald approved these changes

2021-06-18 09:15 UTC, merged

2021-06-18 09:19 UTC, pmvald commented
@Fodrigoal I made some changes and merged the branch. Please take a look at my changes to get a better idea of the design system. Yes, in general we try to be minimalist and use classes/style as least as possible. In this case, the `<menu>` styles already do most of things for us. For menu, we always have to style the "active" (=selected) item as well (look at my code). I also changed the button color to "inherit". Your follow-up assignment: what is inherit style, and why I changed the color to inherit?
-

2021-06-18 10:11 UTC, Fodrigoal commented
Inherit is a keyword that specifies that a property should inherit its value from its parent element. You used it so the button color would emulate the color from its parent (li). Otherwise, the button would change to blue due to a rule for button tags on the _reboot.scss file.

2021-06-18 10:16 UTC, Fodrigoal commented
Would you mind explaining to me why we need to style the active item in the menu and why didn't you change the <i> font size and put it nested on the button?

Something like this:
```
.s-btn-menu {

 
    li > button {
        color: inherit;

        & > i {
            font-size: $font-size-sm*2;
        }

        & > p {
            font-size: $font-size-sm;
        }

        &.active {
            color: $primary-color;
        }
    }
}
```

Thanks @pmvald