task-015 v1.0
Appers-lab/billihomes-frontend pull request #36
Opened 2021-06-16 02:20 UTC by j-ae

I finished this task but I have two questions 

**1. Can I choose colors except theme colors?**
I saw that there are some variables for colors in _variables.sass, but I think they are not good for this sidebar design.

**In this case, what is your recommendation?** 
Should I ask you to add some colors at _variables.sass? or The colors aren't matter in this stage tasks? 
(At this time, I just copied them from the codepen example.)

**2. Should I add local variables(bg color, text color) in css?**
https://github.com/Appers-lab/billihomes-frontend/blob/31d88fb659eba58af29d811152fa78f6616afcf9/-sass/styles/_footers.scss#L2-L4
I found that there are variables for color in a scss file.
I like the idea. **Should I also add the variables of colors in my scss file? Is it required?**

2021-06-16 23:59 UTC, pmvald requested changes
@j-ae I made code review

2021-06-16 23:59 UTC, pmvald commented on -sass/styles/_admin-bars.scss
> +    width: 15rem;
for spacing units lets use $spacer varibale. It is set to 16px by default. So this could be `width: 15*$spacer`

2021-06-16 23:59 UTC, pmvald commented on -sass/styles/_admin-bars.scss
> +    background-color: #19222a;
You can define scss variables on top of this scss file. Like $admin-bar-bg-color, etc.

2021-06-16 23:59 UTC, pmvald commented on -sass/styles/_admin-bars.scss
> +        line-height: 4.5rem;
not sure if line-height is a good style ... how about padding?

2021-06-16 23:59 UTC, pmvald commented on -sass/styles/_admin-bars.scss
> +                content: ">";
this type of styling is not flexibale. If you change the width to something other than `15rem` then this will show on the wrong place. For now we actually don't need such a symbol, so just remove it (but if we ever need such a symbol it has to be added as a separate `<div>` with `margin-left:auto` in a flex container which causes it to be pushed to the right side)

2021-06-16 23:59 UTC, pmvald commented on -sass/styles/_admin-bars.scss
> +        line-height: 3rem;
all these should be expressed in terms of `$spacer`. Replace line-height with padding

2021-06-17 00:14 UTC, j-ae commented on -sass/styles/_admin-bars.scss
> +    width: 15rem;
That's interesting idea. Should I also change the font size unit from rem->$spacer? Or just margin, padding or etc for spacing?

2021-06-17 01:01 UTC, j-ae commented on -sass/styles/_admin-bars.scss
> +                content: ">";
" `<div>` with `margin-left:auto` in a flex container which causes it to be pushed to the right side"
Thanks!

2021-06-17 01:14 UTC, j-ae commented on -sass/styles/_headers.scss
> +    }
I forgot to add this lines at last commit. Can you also review it?

2021-06-17 01:17 UTC, j-ae commented on -sass/styles/_headers.scss
> +
I forgot to add this lines at last commit. Can you review it?

2021-06-17 01:18 UTC, j-ae commented
@pmvald, Thanks you for the code review. I fixed them.

2021-06-18 04:19 UTC, pmvald commented on -sass/styles/_admin-bars.scss
> +    width: 15rem;
only spacing. For font we either use rem, or even better soem standard sizes like `$font-size-base, $font-size-sm, ...` bootstrap has quite a few variables like these for font (see `bootstrap5/_variables.scss`'

2021-06-18 05:15 UTC, pmvald approved these changes

2021-06-18 05:16 UTC, merged

2021-06-18 05:19 UTC, pmvald commented
@j-ae Good! I merged the branch. I also added "css variables" to the code. I plan to write a guide about css variables soon so that interns start using it. But for now, since you did this task, here is your task follow-up assignment: take a look at the changes that I made and write a brief explanation on how I used css variables, and in particular how they make it easier to write modifiers (notice modifiers like --no-shadow, --narrow and --dark). Make your writeup easy to understand. I like to use it as part of the guide (we also make guides in addition to code ...)

2021-06-18 23:02 UTC, j-ae commented
**What is CSS Variable?**
CSS Variable is a variable for CSS. 
The syntax is "--name" and it can be used with var( ). 
ex)
```
// set css variable
 --header-bg-color: white;

// use css variable
.header {
  background-color: var(--header-bg-color);
}
```
**Set Modifiers with CSS variable**
The css variable is especially useful to write modifiers(ex: --no-shadow, --narrow and --dark).
When you change the CSS variable(--name), the all places(var(--name)) which have the variable update the css property according to right specificity. 
ex)
```
.s-main-header {
  // css variables to build the header from
  --padding-top: 1rem;
  --padding-bottom: 1rem;
  --box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  --text-color: #{$primary-color};
  --bg-color: white;

  // main body styles
  padding-top: var(--padding-top);
  padding-bottom: var(--padding-bottom);
  box-shadow: var(--box-shadow);
  background-color: var(--bg-color);

  // Modifiers:
  &--dark {
    --text-color: white;
    --bg-color: #{$primary-color};
  }
  &--no-shadow {
    --box-shadow: unset;
  }
  &--narrow {
    --padding-top: 0.5rem;
    --padding-bottom: 0.5rem;
  }
}
```

**CSS Variable with SASS Variable**
In the recent SASS, to set CSS Variable with the SASS Variable, it only works within interpolation(#{ }).
ex)
```
$accent-color: #fbbc04;
:root {
  // WRONG, will not work in recent Sass versions.
  --accent-color-wrong: $accent-color;

  // RIGHT, will work in all Sass versions.
  --accent-color-right: #{$accent-color};
}
```
source: [https://sass-lang.com/documentation/breaking-changes/css-vars](https://sass-lang.com/documentation/breaking-changes/css-vars)

**CSS Variable vs SASS Variable**
CSS Variable(--name) can access to DOM which means you can change the variable dynamically using JavaScript or Media Query.
On the other hand, SASS($name) Variable is a variable in a preprocess. After compiling(sass -> css), you can't change the variable becaues it doesn't exist.