Miyabi
Appers-lab/billihomes-frontend pull request #37
Opened 2021-06-16 08:24 UTC by miyabitanimchi

@pmvald 
It is my first task, so please let me know if there are any big/small mistakes or my misunderstandings . 
Thank you.

2021-06-16 09:23 UTC, miyabitanimchi commented
Oh, I'm sorry, I think I misunderstood about the branch name. I should've created one with the task number on my local branch and pushed that branch? I made a branch with my name instead...

2021-06-16 16:33 UTC, miyabitanimchi commented
Hi @j-ae ! 
Oh I got it, thank you so much! 🙏

2021-06-16 23:44 UTC, pmvald requested changes
@miyabitanimchi Good, I made some suggestion. Please attend

2021-06-16 23:44 UTC, pmvald commented on -sass/_styles.m.scss
> +@import "styles/action-sheet.m";
Good

2021-06-16 23:44 UTC, pmvald commented on -sass/styles/_action-sheet.m.scss
> +    font-size: 0.8125rem;
how about $font-size-sm? (bootstrap has several scss variables related to font size, pelase check them in bootstrap5/_variables. scss, I guess we should use font-size-sm or something similar to make the text one level smaller)

2021-06-16 23:44 UTC, pmvald commented on -sass/styles/_action-sheet.m.scss
> +    color: $gray-900;
For colors lets use the them colors defined in _styles/_varibales, like maybe $grey or $light-grey?

2021-06-16 23:44 UTC, pmvald commented on -sass/styles/_action-sheet.m.scss
> +    border-bottom: 1px solid $gray-300;
same here, $grey-300 -> $light-grey/$grey/$dark-grey ...

2021-06-16 23:44 UTC, pmvald commented on -sass/styles/_action-sheet.m.scss
> +      align-items: start;
no need. The `<menu>` tag and its modifier (`menu--column` i guess) are already defined in `/styles/_menu` and contain all these styles.

2021-06-16 23:44 UTC, pmvald commented on -sass/styles/_action-sheet.m.scss
> +        font-size: 0.9375rem;
$font-size-sm

2021-06-16 23:44 UTC, pmvald commented on -sass/styles/_action-sheet.m.scss
> +      color: $red;
$red? no problem just make sure it is defined in `/styles/_variables` (or add it if not)

2021-06-16 23:44 UTC, pmvald commented on -sass/styles/_sections.m.scss
> +  background: $light-grey;
good

2021-06-16 23:44 UTC, pmvald commented on -sass/styles/_sections.m.scss
> +    color: $gray-900;
see above comments

2021-06-16 23:44 UTC, pmvald commented on -sass/styles/_sections.m.scss
> +    background: $white;
just white

2021-06-16 23:44 UTC, pmvald commented on -sass/styles/_sections.m.scss
> +    font-size: 0.9375rem;
h2 normally should be *bigger* than the normal size font ...

2021-06-16 23:44 UTC, pmvald commented on -sass/styles/_sections.m.scss
> +  }
what is content__btn? We only have __content section and no need to add any style to anything inside it. This has to be removed

2021-06-16 23:44 UTC, pmvald commented on -sass/styles/_sections.m.scss
> +  }
remove

2021-06-16 23:44 UTC, pmvald commented on tasks/task-025/action-sheet.html
> +    </article>
Good

2021-06-17 01:28 UTC, miyabitanimchi commented on -sass/styles/_action-sheet.m.scss
> +    font-size: 0.8125rem;
@pmvald Okay for the variable. As you mentioned below, this also shouldn't be h2?

2021-06-18 08:44 UTC, pmvald approved these changes

2021-06-18 08:44 UTC, merged

2021-06-18 08:46 UTC, pmvald commented
@miyabitanimchi I made some changes and merged the branch. Now your follow-up assignment: what changes I made? And why? (particularly see the changes related to the menu)

2021-06-18 17:47 UTC, miyabitanimchi commented
@pmvald 
Thank you for modifying. I checked the changes and my answers are below.
<br/>

### [action-sheet.html / scss]
1.  **close link's style:**
**Changes:** external → inline, color #dc3545 as a variable → red
**My answers:** That variable with the specific color will never be reused to other element and for the color, just pure red was fine. 

2. **font-size**
**Changes:** font-size-sm → font-size-base
**My answers:** Too small. And also for `<h2>`, it shouldn't be smaller than the normal font size.

3. **border color of section**
**Changes:** $grey-300 → $light-grey
**My answers:** I'm sorry, I forgot to fix it. 

4. **scss - nested li and a in section**
**Changes:** li → menu > li,  a → & > a
**My answers:**Since it's possible that other elements will be added in the section tag,  It's better to write with more specific ways. For  parent > first child, style will be applied only the first child of its parent.

### [sections.html / scss]
1.  **background color of s-section:**
**Changes:** $light-grey → #f9f9f9

2.  **font-size and color of h2:**
**Changes:** font-size-lg → font-size-base, color: $dark-grey → black
**My answers:** For the size, too big? For the color, black is easier for users to read since they are titles for each section.

3.  **Way to write a nested element:**
**Changes:** s-section__content → &__content
**My answers:**  If it's sass, we can write like this and it allows us to read scss files easier and more simple. 

4.  **border-top / bottom on s-section__content:**
**Changes:** border-top and bottom are added
**My answers:**  It makes users easily recognize a border of the title areas and the content areas. 

<br/>
I have questions:

1. For the style of the close link on action-sheet, is there any reason that you used inline css? Are there any rules for when you should use inline or external?

2. For the background of s-section, you changed the color from $light-grey to #f9f9f9. You didn't make a variable for this because that color would be used only on this file?

<br/>
Thank you, and also let me know if my answers are wrong.

2021-06-22 00:52 UTC, miyabitanimchi commented
@pmvald 
Hi, I would like to take this task.

2021-06-22 15:56 UTC, pmvald commented
@miyabitanimchi Good! For the close link style: we don't need such style, this task is only for a general action sheet. The user can change the text color using other utility classes (like `s-mute`, `s-red`, `s-bold`, etc.) We have to MINIMIZE the number of classes and REUSE the classes as much as possible. For the section color, change, yes, it's a good idea to make it into a varibale on top of the page, something like `$section-bg-color`, but right now I'm thinking maybe we just keep the sections all transparent and just change the body background color ... I'll have to double check some standard themes and see if this is a good idea ...