Navjot
Appers-lab/billihomes-frontend pull request #42
Opened 2021-06-22 00:07 UTC by navjot-chahal

@pmvald I was under the impression that the grid should be open at the border and it must implement. So I masked the outer grid section similar to what "client.html" does in the canvas theme reference.

I tried to use the nth-child selector similar to what you mentioned with borders on the right and the bottom and no right borders for every (6n+6) child (right-most grid item). But being a bootstrap grid the elements inside are cascaded in a row-based flexbox. So there are no special attributes present in the last row logos that we can use in the nth-child selector to have its bottom-border removed.

I assume that we wanted this layout to work for any number of logos, so that's why my code was very long previously. But for this pull in order to use nth-child, I had to hard code the "border-bottom: none" for the last four logos. This is not what I initially thought, as this works for 16 logos (given). Please advise if this is acceptable or if there is a better way to implement this with nth-child.

PS: Thanks for your patience.

2021-06-27 08:51 UTC, navjot-chahal commented
@pmvald I have added task 13 additions to this pull request as well. Please review my work.

2021-06-28 15:28 UTC, pmvald requested changes

2021-06-28 15:28 UTC, pmvald commented on -sass/styles/_collapse.scss
> +@keyframes collapse-animation {
good

2021-06-28 15:28 UTC, pmvald commented on -sass/styles/_dropdown.scss
> +    overflow: hidden;
maybe this should also move to the layouts

2021-06-28 15:28 UTC, pmvald commented on -sass/styles/_dropdown.scss
> +    height: 1rem + $menu-link-padding-x;
we usually don't specify the height directly. You may add padding top/bottom - the height becomes whatever it has be

2021-06-28 15:28 UTC, pmvald commented on -sass/styles/_dropdown.scss
> +    @include caret();
where is caret defined?

2021-06-28 15:28 UTC, pmvald commented on -sass/styles/_collapse.scss
> +    &--open > span {
instead of `span` it is more standard to use `:after`

2021-06-28 15:35 UTC, pmvald commented
@navjot-chahal thanks for your work. A few things: 
1. we asked the interns to pick the tasks labelled "help wanted". These tasks are meant for interns and have more detailed and simplified instructions. You picked a task that by chance was not meant for intern. The dropdown task is going to employ web components later ... I recommend you choose a "help wanted" task and move step by step
2. When you pick a task you should notify us (by dropping a line maybe). I didn't know you were working on this task ... 
3. You included task 11 in this pull request. I already closed that task and pull request. Besides, we should never mix or combine tasks. Each task should have its own pull request. Also I see you added a label "help wanted" to this pull request which is not meant to be here. As a team we need to follow the same guideline and avoid doing random stuff (and this is even more important than programming skills itself)
4. nevertheless, I made a few code review comments so that you get some idea. But I recommend you pick a "help wanted" task and be inline with other interns

2021-06-28 19:53 UTC, navjot-chahal commented on -sass/styles/_dropdown.scss
> +    @include caret();
Caret is defined in:
> /-sass/bootstrap5/mixins/_caret.scss

I added it in the same way as bootstrap5 dropdown

2021-06-28 19:53 UTC, navjot-chahal commented on -sass/styles/_dropdown.scss
> +    height: 1rem + $menu-link-padding-x;
Changed in Task 13 - Additions.

2021-06-28 19:53 UTC, navjot-chahal commented on -sass/styles/_dropdown.scss
> +    overflow: hidden;
Changed in Task 13 - Additions.

2021-06-28 19:57 UTC, navjot-chahal commented
@pmvald Changes added as requested. I will make sure I will follow the instruction carefully.

2021-07-01 07:29 UTC, closed without merging