Joergen
Appers-lab/billihomes-frontend pull request #49
Opened 2021-06-26 00:28 UTC by joergenreyes

Pull request to merge 'joergen' into 'main'

2021-06-26 19:01 UTC, pmvald requested changes
@joergenreyes I made some code review - please attend - thanks

2021-06-26 19:01 UTC, pmvald commented on -sass/styles/_chip.scss
> +    background-color: $light-grey;
maybe define this by a css variable like `var(--bg-color, $light-grey)`

2021-06-26 19:01 UTC, pmvald commented on -sass/styles/_chip.scss
> +    border-radius: 1000px;
maybe `border-radius: var(--chip-height)`?

2021-06-28 21:03 UTC, joergenreyes commented
@pmvald I have implemented the changes to the SCSS chips document.

2021-06-29 04:51 UTC, pmvald approved these changes

2021-06-29 04:52 UTC, merged

2021-06-29 04:52 UTC, pmvald commented
@joergenreyes cool! thanks!