Task 33
Appers-lab/billihomes-frontend pull request #57
Opened 2021-06-30 15:23 UTC by miyabitanimchi

Good morning @pmvald . Problem solved, I just pushed again and this time they asked me for my username and my personal access token. I input them and could push.

2021-07-02 02:34 UTC, pmvald requested changes
@miyabitanimchi I made code review. You defined too many classes! This task can be done by just 3 or 4 elements at most ...

2021-07-02 02:34 UTC, pmvald commented on -sass/styles/_footers.m.scss
> +  font-size: $font-size-sm;
Good

2021-07-02 02:34 UTC, pmvald commented on -sass/styles/_footers.m.scss
> +  }
No need to define a class for everything! These styles can easily be replaced by layer 0 classes "mb-h text-center"

2021-07-02 02:34 UTC, pmvald commented on -sass/styles/_footers.m.scss
> +  }
same as above

2021-07-02 02:34 UTC, pmvald commented on -sass/styles/_footers.m.scss
> +  &__contact-info {
you already defined one flexbox above, isn't it enough? Try to minimize the number of classes ... I believe just one flexbox with justify-content:center is enough

2021-07-02 02:34 UTC, pmvald commented on -sass/styles/_footers.m.scss
> +    .bi-envelope {
Never include a specific icon in a layer 1 style, which is meant to be a general purpose class (what if someone uses another icon name?) - just use the tag `i` for icon -- and BTW, we don't even need this style - just add "me-q" to the html icon

2021-07-02 02:34 UTC, pmvald commented on -sass/styles/_footers.m.scss
> +      margin-right: 0.5 * $spacer;
same as above

2021-07-02 02:34 UTC, pmvald commented on -sass/styles/_footers.m.scss
> +    }
same as above

2021-07-02 02:34 UTC, pmvald commented on -sass/styles/_footers.m.scss
> +    &__term-policy {
why so many classes? if you want margin/padding just use bootstrap helpers that we make (m-q, m-h, m-1, p-2, etc.)

2021-07-02 08:12 UTC, miyabitanimchi commented
Hi @pmvald, thank you for your review. I modified the files so please check. <br/>
I have a question but what do "h" and "q" mean in bootstrap helpers? (like me-q's "q" and mb-h's "h").

2021-07-02 21:08 UTC, pmvald approved these changes
@miyabitanimchi I made changes. That's how it should be! Please review my changes. For mobile pages it is better to show the icons and text in stack layout than horizontal (like using d-flex) because the screen is narrow and things may squeeze. Also, secondary important text should become grey as I did.

2021-07-02 21:08 UTC, merged

2021-07-03 03:19 UTC, pmvald commented
> Hi @pmvald, thank you for your review. I modified the files so please check.
> 
> I have a question but what do "h" and "q" mean in bootstrap helpers? (like me-q's "q" and mb-h's "h").

@miyabitanimchi These are our own inventions!!! Bootstrap only has numbers: m-1, m-2, etc. and they have pretty random values. We made them more organized. q mean quarter (0.25) and h means half (0.5). So m-1q means margin `1.25*$spacer`, p-hq means padding `0.75*$spacer`. Basically by these combination we can create all practical values for spaces